---
- lineinfile:
    path: /etc/systemd/system/docker.service.d/http-proxy.conf
    line: "[Service]\nEnvironment=http_proxy=\"http://wwwproxy.unimelb.edu.au:8000\"\nEnvironment=https_proxy=\"http://wwwproxy.unimelb.edu.au:8000\"\nEnvironment=ftp_proxy=\"http://wwwproxy.unimelb.edu.au:8000\"\nEnvironment=no_proxy=localhost,127.0.0.1,127.0.1.1"
    create: yes