---
- name: Gather facts of remote host
  setup:
    gather_subset: all

- name: install dependencies
  tags: always
  become: yes
  apt:
    name: ['apt-transport-https', 'build-essential', 'ca-certificates', 'curl', 'git', 'python-pip', 'python-setuptools', 'software-properties-common', 'default-jdk', 'scala']
    state: latest
    install-recommends: no
    update-cache: yes

- name: Update python-pip
  tags: always
  become: yes
  pip:
    name: ['pip']
    state: latest